paths:
  results: "./results/"
  models: "./models/"
  data: "./data/"

data:
  name: "cifar10"
  image_width: 32
  image_height: 32
  n_channels: 3
  n_classes: 10

grid_2d:
  height: 64
  width: 128

grid_3d:
  n_layers: 16

training:
  batch_size: 512
  learning_rate: 1.0e-4
  n_epochs: 1000
  n_workers: 2  # set to 0 for debugging

testing:
  batch_size: 2000

tracking:
  train_stats_every_n_epochs: 1
  test_stats_every_n_epochs: 10
  save_model_every_n_epochs:  10

visualization:
  n_samples: 16
  color_map: "seismic"
  interpolation: null # "null" stands for "None", "spline16", "sinc"
  resolution: 250
