paths:
  results: "./results/"
  models: "./models/"
  data: "./data/"

data:
  name: "fashion_mnist"
  image_width: 28
  image_height: 28
  n_channels: 1
  n_classes: 10

grid_2d:
  height: 64
  width: 16

grid_3d:
  n_layers: 16

training:
  batch_size: 128
  learning_rate: 4.0e-4
  n_epochs: 10000
  n_workers: 2  # set to 0 for debugging

testing:
  batch_size: 2000

tracking:
  train_stats_every_n_epochs: 1
  test_stats_every_n_epochs: 10
  save_model_every_n_epochs:  10

visualization:
  n_samples: 40
  color_map: "bwr"
  interpolation: null # "null" stands for "None", "spline16", "sinc"
  resolution: 250
